version: '3.8'

services:
  redis1:
    container_name: redis1
    image: redis:latest
    command: >
      redis-server --requirepass "E9D6ECBB-3E2A-4745-B62B-006E2F80A9A8" --tls-port 6379 --port 0
      --tls-cert-file /usr/local/etc/redis/redis1.crt
      --tls-key-file /usr/local/etc/redis/redis1.key
      --tls-ca-cert-file /usr/local/etc/redis/ca.crt
      --tls-auth-clients no
      --tls-replication yes
      --appendonly yes
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
    volumes:
      - ./redis1:/usr/local/etc/redis
      - ./myCA/ca.crt:/usr/local/etc/redis/ca.crt
    ports:
      - "7100:6379"

  redis2:
    container_name: redis2
    image: redis:latest
    command: >
      redis-server --requirepass "E9D6ECBB-3E2A-4745-B62B-006E2F80A9A8" --tls-port 6379 --port 0
      --tls-cert-file /usr/local/etc/redis/redis2.crt
      --tls-key-file /usr/local/etc/redis/redis2.key
      --tls-ca-cert-file /usr/local/etc/redis/ca.crt
      --tls-auth-clients no
      --tls-replication yes
      --appendonly yes
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
    volumes:
      - ./redis2:/usr/local/etc/redis
      - ./myCA/ca.crt:/usr/local/etc/redis/ca.crt
    ports:
      - "7101:6379"

  redis3:
    container_name: redis3
    image: redis:latest
    command: >
      redis-server --requirepass "E9D6ECBB-3E2A-4745-B62B-006E2F80A9A8" --tls-port 6379 --port 0
      --tls-cert-file /usr/local/etc/redis/redis3.crt
      --tls-key-file /usr/local/etc/redis/redis3.key
      --tls-ca-cert-file /usr/local/etc/redis/ca.crt
      --tls-auth-clients no
      --tls-replication yes
      --appendonly yes
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
    volumes:
      - ./redis3:/usr/local/etc/redis
      - ./myCA/ca.crt:/usr/local/etc/redis/ca.crt
    ports:
      - "7102:6379"
  redisinsights:
    container_name: redisinsights
    image: redis/redis-stack:latest
    ports:
      - "8001:8001"
