version: '3'

services:
  redis1:
    image: redis:latest
    container_name: redis1
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6379
    networks:
      - redis-cluster

  redis2:
    image: redis:latest
    container_name: redis2
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6379
    networks:
      - redis-cluster

  redis3:
    image: redis:latest
    container_name: redis3
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6379
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
