version: '3'

services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=secretcookie
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq1_data:/var/lib/rabbitmq
    container_name: rabbitmq1

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=secretcookie
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    depends_on:
      - rabbitmq1
    #command: bash -c "sleep 10; rabbitmqctl stop_app; rabbitmqctl join_cluster rabbit@rabbitmq1; rabbitmqctl start_app"
    volumes:
      - rabbitmq2_data:/var/lib/rabbitmq
    container_name: rabbitmq2

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq3
    environment:
      - RABBITMQ_ERLANG_COOKIE=secretcookie
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    depends_on:
      - rabbitmq1
    #command: bash -c "sleep 20; rabbitmqctl stop_app; rabbitmqctl join_cluster rabbit@rabbitmq1; rabbitmqctl start_app"
    volumes:
      - rabbitmq3_data:/var/lib/rabbitmq
    container_name: rabbitmq3

volumes:
  rabbitmq1_data:
  rabbitmq2_data:
  rabbitmq3_data:

