services:
  db:
    container_name: pg
    image: "postgres:16"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - internal
      - external
    env_file:
      - stack.env
    ports:
      - 5432:5432
  pgadmin4:
    container_name: pgadmin4
    image: "dpage/pgadmin4"
    volumes:
      - pgadmin4:/var/lib/pgadmin
    ports:
       - "10090:80"
    networks:
      - internal
      - external
    env_file:
      - stack.env
networks:
  internal:
    name: internal
    internal: true
    attachable: true
  external:
    name: external
    attachable: true
volumes:
  postgres:
    name: postgres
    driver: local
    driver_opts:
      type: none
      device: /opt/pg
      o: bind
  pgadmin4:
    name: pgadmin4
    driver: local
    driver_opts:
      type: none
      device: /opt/pgadmin
      o: bind